services:
  estudy-backend:
    container_name: estudy-backend
    build:
      context: ./estudy-backend
      dockerfile: Dockerfile
    image: estudy-backend:latest
    networks: 
      - net
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_USER: db_user
      DB_PASSWORD: password
      DATAGEN: 1
      DATA_MIGRATION_SERVICE: "http://datasync:8081"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      API_KEY: key

  estudy-frontend:
    container_name: estudy-frontend
    build:
      context: ./estudy-frontend
      dockerfile: Dockerfile
    image: estudy-frontend:latest
    networks: 
      - net
    ports:
      - 3000:3000
      
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - estudy-data:/var/lib/mysql
    networks: 
      - net
    ports:
      - 3306:3306
    expose:
      - 3306:3306
    environment:
      MYSQL_USER: db_user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: estudy
    
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks: 
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "ratings"

    command: --auth
    volumes:
      - ./mongodata:/mongodata/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    networks:
      - net
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=example1
    volumes:
      - ./miniodata:/data
    ports:
      - 9001:9001
      - 9000:9000

  fileupload:
    image: fileupload-api:static
    container_name: fileupload
    networks:
      - net
    environment:
- FRONTEND_HOST=localhost
      - FRONTEND_PORT=3000
      - MINIO_HOST=
      - MINIO_PORT=
      - MINIO_ACCESS_KEY_ID=
      - MINIO_SECRET_ACCESS_KEY=xp9HbJ0nhHjc7H1doP3RNxqC6w257UAC9tEYtgay
      - GIN_MODE=release
    volumes:
      - ./sqlitedata:/app/data
    ports:
      - 8082:8082

  datasync:
    image: datasync:latest
    container_name: datasync
    networks:
      - net
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ratings
      - BACKEND_HOST=estudy-backend
      - BACKEND_PORT=8080
      - BACKEND_KEY=key
      - BACKEND_USER=admin
      - BACKEND_PASSWORD=password
      - GIN_MODE=release
    ports:
      - 8081:8081

  ratings:
    image: ratings:latest
    container_name: ratings
    networks:
      - net
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ratings

    ports:
      - 5065:5065


volumes:
  estudy-data:

networks:
  net:
