name: Build frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: cd into estudy-frontend
        shell: bash
        run: cd estudy-frontend

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package.lock')}}
          restore-keys: node_modules

      - name: Install dependencies
        working-directory: estudy-frontend
        run: npm i

      - name: Build Project
        working-directory: estudy-frontend
        run: npm run build
