name: Build backend

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          ENABLED_LINTERS: JAVA
          DISABLE_LINTERS: "*" # Disable all other linters
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          LINT_DIR: my-java-app  # Change this to your subdirectory
          LANGUAGES: java  # Only run the linter for Java


#      - name: Test with Maven
#        run: | 
#          cd estudy-backend 
#          mvn test


      - name: Build with Maven
        run: | 
          cd estudy-backend 
          mvn clean package 
